In [8]:
import nibabel
import numpy as np
from monai.transforms import AsDiscrete, SaveImage, Compose

# Load the image
image = nibabel.load('/home/the_architect/vr_heart_results/45wq9ozw/labels/P73_labels/P73_labels_pred.nii.gz')
image_data = image.get_fdata()

transforms = Compose([
    AsDiscrete(threshold=0.5),
    SaveImage(output_dir='/home/the_architect/vr_heart_results/45wq9ozw/labels/P73_labels',
             output_postfix='pred_discrete', 
             output_ext='.nii.gz',
             resample=False)
])

# Apply transforms and verify shape
discrete_data = transforms(image_data)
print(discrete_data.shape)


2025-03-03 17:55:45,122 INFO image_writer.py:197 - writing: /home/the_architect/vr_heart_results/45wq9ozw/labels/P73_labels/0/0_pred_discrete.nii.gz
torch.Size([512, 512, 281])
Original image data:  [[[0.03258974 0.03258974 0.03234433 ... 0.03296124 0.03296124 0.03333683]
  [0.03258974 0.03258974 0.03234433 ... 0.03296124 0.03296124 0.03333683]
  [0.03258974 0.03258974 0.03228326 ... 0.03271313 0.03271313 0.03321117]
  ...
  [0.03314852 0.03314852 0.03289904 ... 0.03252823 0.03252823 0.03296124]
  [0.03302355 0.03302355 0.03296124 ... 0.03246681 0.03246681 0.03271313]
  [0.03302355 0.03302355 0.03296124 ... 0.03246681 0.03246681 0.03271313]]

 [[0.03258974 0.03258974 0.03234433 ... 0.03296124 0.03296124 0.03333683]
  [0.03258974 0.03258974 0.03234433 ... 0.03296124 0.03296124 0.03333683]
  [0.03258974 0.03258974 0.03228326 ... 0.03271313 0.03271313 0.03321117]
  ...
  [0.03314852 0.03314852 0.03289904 ... 0.03252823 0.03252823 0.03296124]
  [0.03302355 0.03302355 0.03296124 ... 0.03246

In [3]:
image = nibabel.load('/home/the_architect/vr_heart_results/45wq9ozw/labels/P73_labels/P73_labels_pred.nii.gz')
image_data = image.get_fdata()
print(image_data.shape)

(512, 512, 281)


In [6]:
print(image_data.max())
print(image_data.min())

0.9999512434005737
0.027324529364705086


In [9]:
disc_image = nibabel.load('/home/the_architect/vr_heart_results/45wq9ozw/labels/P73_labels/0/0_pred_discrete.nii.gz')
disc_image_data = disc_image.get_fdata()
# Reshape the data to desired dimensions (512, 512, 281)
disc_image_data = np.transpose(disc_image_data, (0, 3, 2, 1))  # Rearrange axes
disc_image_data = np.squeeze(disc_image_data)  # Remove singleton dimension
print(disc_image_data.shape)
print(disc_image_data.max())
print(disc_image_data.min())

(512, 281, 1, 512)
1.0
0.0


In [ ]:
disc_image = nibabel.load('/home/the_architect/vr_heart_results/45wq9ozw/labels/P73_labels/0/0_pred_discrete.nii.gz')
disc_image_data = disc_image.get_fdata()
# Reshape the data to desired dimensions (512, 512, 281)
disc_image_data = np.transpose(disc_image_data, (0, 3, 2, 1))  # Rearrange axes
disc_image_data = np.squeeze(disc_image_data)  # Remove singleton dimension
print(disc_image_data.shape)
print(disc_image_data.max())
print(disc_image_data.min())

In [8]:
import nibabel

disc_image = nibabel.load('/home/the_architect/vr_heart_results/vr_heart_origin_shifted/P6/original_P6_labels.nii.gz')
disc_image_data = disc_image.get_fdata()
print(disc_image_data.shape)
print(disc_image_data.max())
print(disc_image_data.min())

(512, 512, 64)
0.0
0.0


In [5]:
print(disc_image_data)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
